ai:
  advanced_optimization:
    enabled: true
    use_hierarchical: true
    use_scipy: true
    use_time_series_cv: true
  data_decay_rate: 0.4
  enable: true
  genetic_algorithm:
    crossover_rate: 0.8
    generations: 10
    mutation_rate: 0.1
    population_size: 20
  model_save_path: models/ai_model.pkl
  model_type: machine_learning
  models_dir: models
  optimization_interval: 30
  scoring:
    rise_benchmark: 0.1
    rise_weight: 0.3
    risk_benchmark: 0.2
    risk_weight: 0.1
    speed_weight: 0.2
    success_weight: 0.4
  train_test_split_ratio: 0.8
backtest:
  charts_dir: charts
  default_end_date: '2024-12-31'
  default_start_date: '2023-01-01'
  end_date: '2025-06-19'
  generate_charts: true
  rolling_step: 63
  rolling_window: 252
  start_date: '2022-01-01'
data:
  cache_dir: cache
  cache_enabled: true
  data_file_path: data/SHSE.000852_1d.csv
  data_source: akshare
  frequency: 1d
  history_days: 1000
  index_code: SHSE.000852
logging:
  backup_count: 5
  file: logs/system.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  max_bytes: 10485760
notification:
  email:
    password: your_password
    recipients:
    - your_email@example.com
    sender: quant_system@example.com
    smtp_port: 587
    smtp_server: smtp.example.com
    username: your_username
  logs_dir: logs
  methods:
  - console
  - email
results:
  images_path: results/images
  save_detailed: true
  save_path: results
  tables_path: results/tables
strategy:
  confidence_weights:
    final_threshold: 0.7
    rsi_low_threshold: 41
    rsi_oversold_threshold: 25
  max_days: 29
  rise_threshold: 0.03
system:
  log_file: logs/system.log
  log_level: INFO
  mode: backtest
