# 策略配置文件
# 包含所有策略相关的参数和配置

# 基础策略参数
strategy:
  rise_threshold: 0.05           # 涨幅阈值 - 判断相对低点的核心参数
  max_days: 19                   # 最大观察天数 - 在多少天内观察涨幅
  ma_periods: [5, 10, 20, 60]    # 移动平均线周期
  rsi_period: 14                 # RSI指标周期
  macd_fast: 12                  # MACD快线周期
  macd_slow: 26                  # MACD慢线周期
  macd_signal: 9                 # MACD信号线周期
  bb_period: 20                  # 布林带周期
  bb_std: 2                      # 布林带标准差倍数
  results_dir: results           # 策略结果保存目录

# 置信度权重配置
confidence_weights:
  rsi_oversold: 0.3              # RSI超卖权重
  rsi_oversold_threshold: 31     # RSI超卖阈值
  rsi_low: 0.2                   # RSI偏低权重
  rsi_low_threshold: 42          # RSI偏低阈值
  ma_all_below: 0.3              # 所有均线下方权重
  ma_partial_below: 0.2          # 部分均线下方权重
  bb_lower_near: 0.2             # 靠近布林带下轨权重
  bb_near_threshold: 1.02        # 布林带接近阈值
  macd_negative: 0.1             # MACD为负权重
  recent_decline: 0.2            # 近期下跌权重
  decline_threshold: -0.05       # 下跌阈值
  final_threshold: 0.49999999999999994 # 最终置信度阈值

# 策略评分配置
scoring:
  success_weight: 0.5            # 成功率评分权重
  rise_weight: 0.3               # 涨幅评分权重
  rise_benchmark: 0.1            # 涨幅评分基准
  days_weight: 0.2               # 达标天数评分权重
  days_benchmark: 10.0           # 达标天数评分基准

# 风险控制配置
risk:
  min_confidence: 0.6            # 最小置信度阈值
  max_daily_signals: 3           # 每日最大信号数
  cooldown_days: 5               # 信号冷却天数

# 参数优化范围配置
optimization:
  genetic_algorithm:
    population_size: 20          # 遗传算法种群大小
    generations: 10              # 遗传算法迭代代数
    crossover_rate: 0.8          # 遗传算法交叉概率
    mutation_rate: 0.1           # 遗传算法变异概率
  grid_search:
    cv_folds: 5                  # 网格搜索交叉验证折数
    scoring: f1                  # 网格搜索评分方式
  param_ranges:
    rise_threshold:
      min: 0.05                  # 涨幅阈值最小值
      max: 0.15                  # 涨幅阈值最大值
      step: 0.005                # 涨幅阈值步长
    max_days:
      min: 2                     # 最大天数最小值
      max: 20                    # 最大天数最大值
      step: 1                    # 最大天数步长
    rsi_oversold_threshold:
      min: 25                    # RSI超卖阈值最小值
      max: 35                    # RSI超卖阈值最大值
      step: 1                    # RSI超卖阈值步长
    rsi_low_threshold:
      min: 35                    # RSI偏低阈值最小值
      max: 45                    # RSI偏低阈值最大值
      step: 1                    # RSI偏低阈值步长
    final_threshold:
      min: 0.3                   # 最终置信度阈值最小值
      max: 0.7                   # 最终置信度阈值最大值
      step: 0.05                 # 最终置信度阈值步长 