# 交易策略配置文件
# 定义交易信号生成规则和风险管理参数

trading:
  # 基础交易参数
  enabled: true                     # 是否启用交易信号
  max_position_size: 1.0           # 最大仓位比例 (0-1)
  min_confidence_threshold: 0.3    # 最小置信度阈值
  
  # 信号生成规则
  signal_rules:
    # 强烈买入信号
    buy_strong:
      confidence_min: 0.8           # 最小置信度
      is_low_point: true           # 必须是相对低点
      action: "BUY_STRONG"
      strength: 5
      position_ratio: 0.3          # 建议仓位比例
      risk_level: "LOW"
      
    # 买入信号  
    buy:
      confidence_min: 0.6
      is_low_point: true
      action: "BUY"
      strength: 4
      position_ratio: 0.2
      risk_level: "LOW"
      
    # 弱买入信号
    buy_weak:
      confidence_min: 0.4
      is_low_point: true
      action: "BUY_WEAK" 
      strength: 2
      position_ratio: 0.1
      risk_level: "MEDIUM"
      
    # 观望信号
    watch:
      confidence_min: 0.2
      is_low_point: true
      action: "WATCH"
      strength: 1
      position_ratio: 0.0
      risk_level: "HIGH"
      
    # 持有信号
    hold:
      confidence_max: 0.2
      is_low_point: false
      action: "HOLD"
      strength: 1
      position_ratio: 0.0
      risk_level: "MEDIUM"
      
    # 等待信号
    wait:
      confidence_min: 0.2
      is_low_point: false
      action: "WAIT"
      strength: 0
      position_ratio: 0.0
      risk_level: "MEDIUM"

  # 风险管理
  risk_management:
    # 止损设置
    stop_loss:
      enabled: true
      max_loss_ratio: 0.05         # 最大亏损比例 5%
      trailing_stop: true          # 是否使用移动止损
      
    # 止盈设置  
    take_profit:
      enabled: true
      target_profit_ratio: 0.15    # 目标盈利比例 15%
      partial_profit: true         # 是否分批止盈
      
    # 仓位管理
    position_management:
      max_single_position: 0.3     # 单次最大仓位
      max_total_position: 0.8      # 总最大仓位
      diversification_min: 3       # 最小分散化股票数量
      
    # 连续错误处理
    error_handling:
      max_consecutive_errors: 3    # 最大连续错误次数
      error_penalty_days: 1        # 错误惩罚天数
      auto_reduce_position: true   # 是否自动减仓

  # 时间控制
  timing:
    # 交易时间窗口
    trading_hours:
      market_open: "09:30"         # 市场开盘时间
      market_close: "15:00"        # 市场收盘时间
      
    # 执行时间设置
    execution_schedule:
      morning_check: "09:25"       # 晨间检查时间
      daily_training: "19:00"      # 日常训练时间
      evening_report: "18:00"      # 晚间报告时间
      
    # 禁止交易日期
    blackout_dates:
      - "2024-12-31"               # 年末
      - "2025-01-01"               # 元旦
      # 可以添加更多禁止交易的日期

  # 通知设置
  notifications:
    # 信号通知
    signal_notifications:
      buy_strong: true             # 强买信号通知
      buy: true                    # 买入信号通知  
      buy_weak: false              # 弱买信号不通知
      watch: false                 # 观望信号不通知
      
    # 风险通知
    risk_notifications:
      stop_loss_triggered: true    # 止损触发通知
      high_volatility: true        # 高波动通知
      consecutive_errors: true     # 连续错误通知
      
    # 日常通知
    daily_notifications:
      morning_briefing: true       # 晨间简报
      evening_summary: true        # 晚间总结
      weekly_report: true          # 周报
      
  # 回测验证
  backtesting:
    enabled: true                  # 是否启用回测验证
    validation_days: 30            # 验证天数
    min_success_rate: 0.6          # 最小成功率
    benchmark_comparison: true     # 是否与基准比较

  # 高级设置
  advanced:
    # 动态调整
    dynamic_adjustment:
      enabled: true                # 启用动态调整
      volatility_factor: true      # 波动率因子
      volume_factor: true          # 成交量因子
      
    # 机器学习增强
    ml_enhancement:
      feature_importance: true     # 特征重要性分析
      model_ensemble: false        # 模型集成
      online_learning: true        # 在线学习
      
    # 市场状态识别
    market_regime:
      bull_market_threshold: 0.05  # 牛市阈值
      bear_market_threshold: -0.05 # 熊市阈值
      sideways_threshold: 0.02     # 震荡市阈值 